### PR TITLE
Update 01_padrino-admin.html.md code and grammar

### PR DESCRIPTION
**Pull request by hobs**
Fixed incorrect spelling of project_module in access control example , re-worded some sentences to flow "better".

### CODE REVIEW

**Comment by nesquena** [comment]
Thanks

**Comment by hobs** [comment]
This is my first PR on github, so please let me know if this needs any updating/fixing to meet standards. 

I have been reviewing Padrino docs and would like to submit additional changes in the future, so any hints or best practices would be appreciated!

**Comment by nesquena** [comment]
> I have been reviewing Padrino docs and would like to submit additional changes in the future, so any hints or best practices would be appreciated!

Please do!

**Comment by wikimatze** [comment]
@hobs thanks for the effort and congratulations for your first merged PR. Can you wait a little bit with future improvements because I changed a lot in the documentation.

**Comment by hobs** [comment]
@wikimatze certainly. I will keep an eye out for your changes and hold back anything until then. 
Thanks for the guidance.

**Comment by wikimatze** [comment]
May changes are over, you can now include your changes.

**Pull request merged**
