### PR TITLE
Blog tutorial improvements

### LINKED ISSUE #119: Blog Tutorial Improvements
I ran through the blog tutorial to verify accuracy, and I made a few observations that could translate into improvements.

## Remove: Section on updating database configuration manually from Heroku DATABASE_URL variable

As this step technically isn't needed to complete the tutorial, I can't help but wonder if it should just be removed. As the values won't match up to what the user would be seeing, I wonder if it might be a source of confusion to newcomers.

## Remove: Addition to dependency_paths

Looks like `default_dependency_paths` already includes this path, allowing us to remove this step.

## Consistency: Settle on `bundle exec rake` or `padrino rake`

I've never seen `padrino rake` until following the tutorial. Maybe someone else can advise whether one or the other is better suited.

## Remove: Tweak to `db/seeds.rb`

I was prompted for a username and password when seeding. I think this can be safely removed.

<hr>

I'm willing to take care of these items, barring no objections from the core team.

### PR DESCRIPTION
**Pull request by adam12**
A few improvements as discussed in #119 

Closes #119

### CODE REVIEW

**Comment by nesquena** [comment]
cc @wikimatze can you review the changes here and see what you think?

**Comment by wikimatze** [comment]
@adam12 skipping the heroku step make the whole section obsolete - then you don't need to deploy the example app on production.

**Comment by adam12** [comment]
> skipping the heroku step make the whole section obsolete

Not sure I follow. The deployment to Heroku is still there, but with a few pieces removed that weren't required to complete a production deploy:

1. Static database configuration
2. Static seed data

Was there something in those two sections you wanted to retain?

**Comment by wikimatze** [comment]
Think I had problems with the heroku deployment and the passwords, that's why I put it on. It would be okay, if we would leave those steps to the user since it's related to the `heroku` vendor.

**Comment by adam12** [comment]
@wikimatze Let's hold off merging this - I think I found a bug in padrino-core that needs to be patched first.

**Comment by adam12** [comment]
During the migration that adds the account FK to posts, we reference two ActiveRecord models.

In the past this involved appending `dependency_paths`, but I believe this shouldn't be necessary for a tutorial (broken UX). This path exists correctly further down the stack.

Unfortunately, all Rake tasks for ActiveRecord (and Sequel IIRC) ignore `models/` when loading dependencies. This means our models are not available inside the `migrate` task.

This could likely be solved through at least 4 separate ways. Open to comments on one/all?

1. Leave tutorial as is - instruct user to update `dependency_paths` in `before_load!` hook.
2. Update some of the rake tasks to not load the skeleton environment, but the full environment. (my PR for this is here: https://github.com/padrino/padrino-framework/pull/2104)
3. Explicitly require the models at the top of our migration (see below).
4. Define stub models inside our migration (see below).

Code for solution 3
```ruby
Padrino.require_dependency "models/account"
Padrino.require_dependency "models/post"

class AddAccountToPost < ActiveRecord::Migration
  def self.up
    change_table :posts do |t|
      t.integer :account_id
    end

    first_account = Account.first
    Post.all.each { |p| p.update_attribute(:account, first_account) }
  end

  def self.down
    change_table :posts do |t|
      t.remove :account_id
    end
  end
end
```

Code for solution 4
```ruby
class AddAccountToPost < ActiveRecord::Migration
  class Account < ActiveRecord::Base; end
  class Post < ActiveRecord::Base
    belongs_to :account
  end

  def self.up
    change_table :posts do |t|
      t.integer :account_id
    end

    first_account = Account.first
    Post.all.each { |p| p.update_attribute(:account, first_account) }
  end

  def self.down
    change_table :posts do |t|
      t.remove :account_id
    end
  end
end
```

Solution 3 runs the risk that later in time, requiring that full model could be brittle.
Solution 4 isn't DRY, but maybe that's not a huge concern.

Any preference? Pros/cons?

**Comment by wikimatze** [comment]
According to @ujifgc mention https://github.com/jeremyevans/sequel/blob/master/doc/migration.rdoc#using-models-in-your-migrations I would not go for solution 3 - and instead take solution 4. We need to make sure that we explain the step we take + we should mention the `dependency_paths` in `before_load!` solution as an alternative so the reader can decide which is the best solution for them.

**Comment by adam12** [comment]
> take solution 4

I've gone ahead and updated to use this solution.

> We should mention the dependency_paths in before_load! solution as an alternative so the reader can decide which is the best solution for them

I didn't add this back in as I think it's negated by the link you posted.

**Comment by wikimatze** [comment]
Hmm, can somebody validate the changes are still valid in the latest release? If not I'm going to do this in the following week and update the guide.

**Comment by adam12** [comment]
This has gone a bit stale, and it seems to resolve around the use of models in the migrations.

Is there any opposition to switching from ActiveRecord to Sequel in the guides, allowing us to use the raw dataset provided by Sequel?

**Comment by wikimatze** [comment]
I think this should be no problem. I'm planning to run the tutorial again over the weekend (weather will be not good here in Berlin). Would you mind rewriting it in Sequel otherwise I would start in a branch and let you do the review.

**Comment by wikimatze** [comment]
Hi Adam, I start working on your improvements under <https://github.com/padrino/padrino-docs/tree/adam12-issue-119/blog-tutorial-improvements>

**Comment by wikimatze** [comment]
@adam12 do you mind it's okay how I change the `admin generation` steps in https://github.com/padrino/padrino-docs/commit/3f09f16e98c706beb8cb88fdb3083cdaee58b66d?

**Comment by wikimatze** [comment]
Pull request for this one under https://github.com/padrino/padrino-docs/pull/142

**Pull request merged**
