### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by ghoshnirmalya**

### CODE REVIEW

**Comment by wikimatze** [comment]
Thank you very much for the improvement.

**Comment by ghoshnirmalya** [comment]
You're welcome :)

**Comment by wikimatze** [comment]
If you have any questions about Padrino and/or how to help us, feel free to join us on [gitter](https://gitter.im/padrino/padrino-framework)

**Comment by ghoshnirmalya** [comment]
Sure. Thanks! :D

**Pull request merged**
