### PR TITLE
Push drafts for 0.12.6 and 0.13.2 releases

### PR DESCRIPTION
**Pull request by nesquena**
Blog posts for upcoming 0.12.6 and 0.13.2 releases cc @padrino/collaborators

### CODE REVIEW

**Comment by wikimatze** [comment]
Looks good!

**Comment by wikimatze** [comment]
When should we make the deployment?

**Comment by nesquena** [comment]
@wikimatze I think we are ready to go now, we can deploy the new posts

**Comment by wikimatze** [comment]
I've deployed with `rake publish`  but the posts appear in `build/blog` are not created in the form: `2016-05-09-padrino-0-13-2-project-flag-bug-fixes-and-component-upgrades/index.html` and that's why they are not showing up. Don't know why so far.

**Comment by nesquena** [comment]
@wikimatze I figured it out, it had to do with the naming of the files (https://github.com/padrino/padrino-docs/commit/b26349ead9bfaf761e06b1d7a49f8a6d980c33c2). Fixed now!

**Pull request merged**
