### PR TITLE
Add section about query string caching.

### PR DESCRIPTION
**Pull request by velvetkevorkian**
This was previously [referenced in the documentation ](https://github.com/padrino/padrino-framework/issues/1729) but seems to have gotten lost when the docs were re-organised.

Not 100% sure if this is the best terminology so open to suggestions for improvement.

### CODE REVIEW

**Comment by adam12** [comment]
Thanks for the PR! :smile:

We should probably test against `master`, as there's ongoing work to remove ActiveSupport, which is where I believe `Hash#slice` would come from (and perhaps even `String#to_param`). Be good to know that this works out of the box without AS as a dependency.

**Comment by wikimatze** [comment]
As @adam12 says, when it's confirmed with master, we can add your well written part into the docs.

**Comment by velvetkevorkian** [comment]
You are correct that both `Hash#slice` and `String#to_param` rely on `ActiveSupport`. I've added a version that works without it, and left the AS version as an optional cleaner version. Without AS it feels a bit clunky, but I'm about at the limits of my Ruby skills here, I'm afraid 😬

**Comment by velvetkevorkian** [comment]
Hi folks, can we merge this or close it if it's not required? Thanks

**Pull request merged**
