### PR TITLE
add the cascading section

### PR DESCRIPTION
**Pull request by namusyaka**
@wikimatze @nesquena @ujifgc  Could you review this?

### CODE REVIEW

**Comment by ujifgc** [comment]
I'm not sure but phrasing looks a bit cryptic.

**Comment by namusyaka** [comment]
@ujifgc Can you give me some advice or commit your improvements into this branch?

**Comment by ujifgc** [comment]
I think we better ask a native speaker.

**Comment by nesquena** [comment]
@ujifgc @namusyaka I took a stab at improving this, let me know what you think.

**Comment by wikimatze** [comment]
I'm fine with @nesquena changes - sounds more like a native speaker.

**Comment by adam12** [comment]
:+1: Reads well to me.

**Pull request merged**
